Kylemc1413/SongCore

Collections.cs
Data/SongFolderEntries.cs
Loader.cs

Song Folders created by mods will show up even if they don't contain any songs

Trolav 2019.12.19: ModSeperateSongFolder

---

HarmonyPatches/StartLevelAndCheckPlatformIfCustomPlatformsIsInstalledPatch.cs
Plugin.cs
SongCore.csproj

Patching Platforms Compatibility

---

HarmonyPatches/BeatmapDataLoaderGetBeatmapDataFromBeatmapSaveData.cs

Allows for other mods to patch these methods

Use base game methods instead of own

---

HarmonyPatches/BeatmapDataLoaderGetBeatmapDataFromBeatmapSaveData.cs

Fix: BeatmapDataLoader uses static methods

---

Loader.cs
manifest.json

Trolav 2020.03.28: Levels from seperate folder (new pack) won't be listed under Custom Levels pack on start anymore

---

Loader.cs

Trolav 2020:04.01 - Fix song deletion for other song folders than CustomLevels (CustomWIPLevels, CachedWIPLevels, SeperateSongFolders.Levels)

Trolav 2020:04.01 - Fix song deletion

---

Collections.cs
Data/SongData.cs
Directory.Build.targets
Loader.cs
Properties/AssemblyInfo.cs
SongCore.csproj
UI/RequirementsUI.cs
manifest.json

* Adds a private `Dictionary<string, CustomPreviewBeatmapLevel>` to `Loader`.
* Levels can be accessed by the static functions `GetLevelById(string)` and `GetLevelByHash(string)`
* Also added Directory.Build.targets which will check manifest.json's version against AssemblyInfo.cs, auto-zip Release builds, and copy to Plugins folder on Build if `BeatSaberDir` is defined in the project.

CustomLevels LevelId Dictionary

---

Loader.cs
UI/requirements.bsml

Here's an initial implementation for reading the song length from the ogg file. It doesn't have error handling yet, and should probably use the old approximation as a fallback when reading from the ogg file fails.
Performance after a system reboot is too slow to be practical, so the calculated song length would need to be cached.

Read song length from ogg file

---

Loader.cs

* Seek from end should increase it's value, so were not seeking at the same place all the time
* Moved const byte[] of findBytes call to private static variable so the garbage collector doesn't need to clean all the created arrays
* Use usings so we can be sure, that FileStream an BinaryReader gets disposed, even on error
I tested it localy and the method returns the same values, but with my testing in only 1ms per file and not 10 ms on an ssd. The only needed change was the seek in te for loop, but the rest cleans this code up a bit

Fixed wrong seek in GetLengthFromOgg

---

HarmonyPatches/AnnotatedBeatmapLevelCollectionCell_RefreshAvailabilityAsync.cs

Since this can be quite misleading for custom songs

Patched out the download icon for custom packs

---

Loader.cs

Added a method to bulk delete songs async

---

Loader.cs
UI/ProgressBar.cs

This PR pushes some things onto the main thread that SHOULD be on the main thread. This way, debugging using the unity profile will work. Also, I made it so the word "song" is singular if there is only 1 song installed (cause I only have one song installed and it was bothering me).

Main Thread Fixes for Debugging + a small touch

---

HarmonyPatches/BeatmapVersionDetectionPatch.cs

Opening a draft PR for this base game issue in case it's not fixed in the final release of 1.20.

Fix beatmap version detection

---

HarmonyPatches/LevelSelectionPatch.cs

As discussed.
Also cleaned up the patch

Show levelAuthorName for all Levels

---

HarmonyPatches/CustomCharacteristicsPatch.cs
HarmonyPatches/CustomSongColorsPatch.cs
HarmonyPatches/LevelSelectionPatch.cs
HarmonyPatches/LoadingPatches.cs
HarmonyPatches/StandardLevelDetailViewRefreshContent.cs
manifest.json

PR based on both the public beta branch on Steam and a dll file from the Oculus update.
Will be merged as soon as the update is officially released on Steam as well.

Update for BS 1.27.0

---

Collections.cs
Plugin.cs

I wasn't aware that we could make the `OnApplicationStart` method async back when I made #75. I remember that @ErisApps  asked me to make the load async as well, so here it is. Might need some testing, though.

Load extra song data asynchronously

---

manifest.json

Updates manifest
Includes raised BS_Utils dependency

Bump version

---

HarmonyPatches/LoadingPatches.cs
Loader.cs
Utilities/Hashing.cs

Less allocation and higher performance for the hashing and the basegame implementation workaround / fix as discussed

Optimizations and Fixes

---

source/SongCore/Collections.cs
source/SongCore/HarmonyPatches/BeatmapVersionDetectionPatch.cs
source/SongCore/HarmonyPatches/CustomCharacteristicsPatch.cs
source/SongCore/HarmonyPatches/CustomSongColorsPatch.cs
source/SongCore/HarmonyPatches/LevelSelectionPatch.cs
source/SongCore/HarmonyPatches/StandardLevelDetailViewRefreshContent.cs
source/SongCore/Loader.cs
source/SongCore/SongCore.csproj
source/SongCore/UI/ColorsUI.cs
source/SongCore/UI/RequirementsUI.cs
source/SongCore/Utilities/Accessors.cs
source/SongCore/Utilities/Hashing.cs
source/SongCore/Utilities/Unzip.cs
source/SongCore/Utilities/Utils.cs
source/SongCore/manifest.json

This contains a couple of optimizations on the side, I tested most of it, but would appreciate it if others could test it to make sure I didn't forget anything.
I modified the beatmap version detection patch for consistency with base game. I don't know which is faster, both are working. But base game is still missing the fallback which is needed for about ~ 3.20% of maps.

Fixes for Beat Saber v1.31.0

---

source/SongCore/Loader.cs

Fix loading issue with separate folder songs

---

source/SongCore/HarmonyPatches/CustomSongColorsPatch.cs

Fix boost colors being hidden when color scheme doesn't support it
