Kylemc1413/SongCore

Loader.cs

Fixed `get_dataPath can only be called from the main thread` exception when using the debug version of UnityPlayer.dll

Fixed exception when using the debug version of UnityPlayer.dll

---

Loader.cs

Before this fix, when deleting a song from a level pack generated for a separate folder, the deleted song's IPreviewBeatmapLevel wouldn't get removed from the beatmap collection (or more accurately, would get re-inserted into the collection during the call to RefreshLevelPacks). This caused the level to still appear in the UI and thrown an exception when selected.

Fix deleting a song from a separate folder's level pack

---

Loader.cs
SongCore.csproj

* Fixes the invalid folder name issue by wrapping calls to Directory.GetFiles() in Try/Catch blocks.
* Fixed Newtonsoft.Json reference to use the file name without a version.

Invalid folder fix

---

manifest.json

This PR was mainly meant to add BSIPA as a dependency to the manifest because it will be a requirement soon™.
Also yeeted the features part from the manifest while we're at it, because it throws warnings and didn't do anything functional.

Daily reminder to add BSIPA to your dependencies

---

Collections.cs
Loader.cs
ProgressBar.cs
Utilities/Hashing.cs

This PR aims to improve the loading speed of custom songs by processing custom songs in a parallel manner.
By general testing, it resulting in a ~3x  performance improvement (however your milage may vary)
However as a side-effect, all dictionaries had to be changed to their Concurrent counterpart (`ConcurrentDictionary`) and with that also breaking the public facing API of SongCore. This means that many mods will be broken and will need a recompile and most likely also a slight change of methods.
Feel free to let me know anything that has to be changed.

Improved custom song loading speed a lot

---

Loader.cs

previous code could've caused a failure to find the last sample in some rare cases
Likely wouldn't have ever caused a problem but best to fix it anyway

fix small mistake in GetLengthFromOgg()

---

Loader.cs

As the title already stated, this PR fixed the issue where the progressbar could possibly jump back and forth due to parallel processing of custom songs.

Fixed progressbar jumping back and forth during song (re)loading

---

Collections.cs
Data/SongFolderEntries.cs
Data/folders.xml
HarmonyPatches/CustomCharacteristicsPatch.cs
Loader.cs
OverrideClasses/SongCoreBeatmapLevelPackCollectionSO.cs

- Added an additional value (CacheZIPs) to "folders.xml"
- If set to "True", ZIPs in that folder will be unzipped to subfolder "Cache"
- If level pack is either CustomLevels ("0") or New Pack ("2"), the cache folder will be a seperate map pack -> New Pack ("2")
- If level pack is CustomWIPLevels, the unzipped beatmaps will be added to CachedWIPLevels ("3" [new])
- Level packs will be overwritten on pack addition / deletion
- Created helper functions for duplicate code
- Added regions for structure
- Added some comments

 Trolav 2020.10.22 - Support beatmap caching for seperate song folders & minor restructuring

---

HarmonyPatches/MainSystemsInitRefreshablePatch.cs
SongCore.csproj

This is a very simple PR which exposes the SongCore refresh ability and load event to the main zenject container via the base game's `IRefreshable` interface and `IObservableChange` event respectively.
**Why?**
Some people (myself included) like to keep dependencies down as much as possible, this helps with that since it's no longer required to reference SongCore directly in order to (just) refresh songs or to (just) know when songs have been loaded (something that I personally realized is the only reason why I'm referencing SongCore for). Mods using Zenject can optionally request the two interfaces through their IDs and use their appropriate methods.
This is especially useful during times of updates where a mod needs to use (occasionally or optionally) use these features but SongCore …

Container Refreshing + Event via Zenject

---

Loader.cs

This allows other modders to Harmony patch the base game method without being bypassed by SongCore.

Replace GetStandardLevelInfoSaveData with base game equivalent

---

HarmonyPatches/LevelSelectionPatch.cs

Round BPM values in level list table, prevent icon overlap

---

HarmonyPatches/LevelSelectionPatch.cs

For now artist/mapper font size is 100%/80%, but artist/title info can also be seen on the right when you select a map.
So I think mapper name should have a priority (increased font size, different color) at least in the list.
<details><summary>Preview</summary>
</details>

Increase mapper name font size and highlight it

---

HarmonyPatches/ClampPatches.cs

Due to `notesInTimeRow` being cleared before exiting `ProcessAllNotesInTimeRow` in patch 1.17.0, our Postfix isn't working anymore and Mapping Extensions maps are broken once again. So we need to repopulate the list.

Fix ProcessAllNotesInTimeRow patch

---

Collections.cs
Data/SongData.cs
HarmonyPatches/LevelSelectionPatch.cs
HarmonyPatches/StandardLevelDetailViewRefreshContent.cs
Loader.cs
Plugin.cs

Improvements to #74.
This will require @Aeroluna to make small changes to CustomJSONData as it's now using a custom implementation of `CustomLevelLoader.LoadCustomLevelInfoSaveData` to load songs with their extra data.

Handle extra song data at load time

---

Loader.cs

Prior to this PR, ExtraSongData would still be added to the caches, regardless of whether the WIP level could be loaded itself.

Only load ExtraSongData when level can load

---

Plugin.cs

Currently, the player's save data is loaded before SongCore is loaded, which means that the patch to `GetBeatmapCharacteristicBySerializedName` is not yet applied and so the game will just fail to retrieve the custom characteristics when loading the player data on launch.

Fix player data loading to account for custom characteristics

---

Data/SongData.cs
HarmonyPatches/CustomSongColorsPatch.cs

This PR allows for assigning the newly added ColorW environment light, as found in 1.22.0. This doesn't work in older versions of the game, but now allows for 1 extra light color and 1 extra boost light color
.

Allow for assigning environment ColorW + boost

---

HarmonyPatches/CustomSongColorsPatch.cs
Plugin.cs
SConfiguration.cs
UI/ColorsUI.cs
UI/RequirementsUI.cs
UI/SCSettingsController.cs
UI/colors.bsml
UI/settings.bsml

Resolves #99.
Also not sure what the intent was behind why boost fallbacked to envLeft and envRight and why environment colours checked for saber colours previously.
UI:

Split "Allow Custom Song Colors" into separate options

---

Collections.cs
Loader.cs
Plugin.cs

Now that Beat Games added back the loading screen, mods are loaded before the game loads the `PlayerData`, making #88 not needed anymore, as SongCore patches are applied once again before that data is loaded.
See #105 for details. We need a better implementation for that specific issue, anyway.

Fix for patch 1.28.0

---

Plugin.cs

Mentioned in https://github.com/Kylemc1413/SongCore/pull/102#issuecomment-1445211574, this is a migration from an old config system so these lines are not needed.
On the off chance someone is migrating from an old config, I'd want to reset this setting to default instead of preserving it as the options are more granular than before.

Remove custom song color config migration

---

HarmonyPatches/CustomSongColorsPatch.cs

This PR makes custom song colors work in multiplayer by adding `MultiplayerLevelScenesTransitionSetupDataSO.Init` as a taget for `SceneTransitionPatch`.

Add multiplayer support for custom song colors

---

HarmonyPatches/CustomSongColorsPatch.cs

This fixes the blackscreening in multiplayer when joining a lobby where a map is currently being played that can't be loaded, for example a DLC map that you don't own.

Fix exception on null difficultyBeatmap

---

Loader.cs
Utilities/Hashing.cs

Just a small improvement using a relative path if the folder is in the install folder to prevent SongCore from reloading all files when the game install is moved or if the UserData and CustomLevels folders are shared across multiple beat saber installs.

Change cache management to use relative path

---

.github/workflows/pr.yml
build/Build.CI.GitHubActions.cs

Accidentally triggering on `main` instead of `master`

Fix CI workflow triggering on incorrect branch

---

source/SongCore/Utilities/Utils.cs

somehow this got slipped past for long while, figured why my light was oddly dim ingame vs editor
shouldnt be an issue for MapColor `a` value seeing it has already been handled elsewhere

Add missing alpha value in color

---

source/SongCore/HarmonyPatches/YeetLegacyBPMEventsPatch.cs

Event with a `type` 10 was introduced as an official BPM change event in 1.8.0 and later reused as a light in 1.18.0. This change disables the conversion of legacy BPM changes to add support for maps with type 10 events as lights, but with a wrong map version.
From the collection of 170k recently (last 2 years) played maps, there were 226 broken maps because of the conversion. Some are quite popular, and 2 ranked maps (1 on BL and 1 on SS). And not a single map that properly utilized these events as BPM changes.
Popular mapping tools (MM/custom saber/CM) never had support for this event, and mappers who tried to use them manually were complaining, so I couldn't even find an example map, let alone a map anyone plays.

Patch out legacy BPM events support
